workspace:
  base: /eslint-config-starlight
  path: src/github.com/Starlilghtpro/eslint-config-starlight

pipeline:
  prepare:
    image: starlightpro/node:9.11.1
    commands:
      - npm install

  test:
    image: starlightpro/node:9.11.1
    commands:
      - npm run test
